#!/bin/sh

ROOT_PATH=`pwd`

start()
{
    stop
    ulimit -c unlimited

    sudo ${ROOT_PATH}/sbin/lmss -p /usr/local/lmss/ -c ${ROOT_PATH}/conf/lmss.conf

    echo 'start...'
}

stop()
{
    exist=`pidof lmss`
    if [ -n "$exist" ]; then
        sudo ${ROOT_PATH}/sbin/lmss -p /usr/local/lmss/ -c ${ROOT_PATH}/conf/lmss.conf -s stop
    fi
    
    #deleted the rtmp.sock
    cf="/usr/local/lmss/conf/lmss.conf"
    unix=`cat $cf |grep "listen" | grep "rtmp.sock"`
    if [ -n "$unix" ]; then
        unix=${unix#*:}
        if [ -n "$unix" ]; then
            unix=${unix%;*}
            if [ -n "$unix" ]; then
                rm -rf $unix
                echo "deleted the rtmp.sock sucess..."
            fi
        fi
    fi
    echo 'stop...'
}

case C"$1" in
    C)
        echo "Usage: $0 {start|stop}"
        ;;
    Cstart)
        start
        echo "Done!"
        ;;
    Cstop)
        stop
        echo "Done!"
        ;;
    C*)
        echo "Usage: $0 {start|stop}"
        ;;
esac

